spring.datasource.url=jdbc:postgresql://localhost:5432/barbearia
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.problemdetails.enabled=false
spring.web.mvc.problemdetails.enabled=false
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
logging.level.org.springframework.security=DEBUG
