spring.datasource.url=jdbc:postgresql://localhost:5432/barbearia
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.problemdetails.enabled=false
spring.web.mvc.problemdetails.enabled=false
jwt.secret=9f3b7c1e4a8d2f6b0c5e9a7d3b1f8c6e2a4d9b7f1c3e5a8b0d6f2c4e9a1b7d5
jwt.expiration=86400000